CI: output debug info on failure
Make the first job fail when the matrix
would be empty. This avoids confusion
about what went wrong in the GitHub
UI.

diff --git a/.github/workflows/build-packages.yaml b/.github/workflows/build-packages.yaml
--- a/.github/workflows/build-packages.yaml
+++ b/.github/workflows/build-packages.yaml
@@ -78,9 +78,11 @@ jobs:
             fi
             tmp+="{\"package\": \"$pkg\", \"build-path\": \"packages/$pkg\"}"
           done
-          if [ "$tmp" != "" ]; then
-            echo "matrix={\"include\":[$tmp]}" >> $GITHUB_OUTPUT
+          if [ "$tmp" = "" ]; then
+            echo "Internal error: no changes detected. Debug info (all_files): $all_files"
+            exit 1
           fi
+          echo "matrix={\"include\":[$tmp]}" >> $GITHUB_OUTPUT
 
   build-image:
     name: build-image
